### ISSUE TITLE
STM32 memory locations off by 10 bytes

### ISSUE THREAD

**Issue by meltdown03** [mcu-debug/memview#1]
I confirmed the memory locations in the STM32411CE Reference Manual as well, but the memories displayed by "memview" are all off by 10 bytes as you can see in this screenshot. "memview" shows the ARR register in 0x4001001c instead of 0x4001002c.

![Screenshot from 2022-10-07 16-30-19](https://user-images.githubusercontent.com/6166536/194659127-7bccda2b-5cad-4268-b5f6-020d011e437e.png)

**Comment by rubenstar** [comment]
I can confirm this offset of 0x10 on my setup. Writing location 0x0e001830 to all F's will read correct for CortexDebug v1.6.4, but fail vor v1.6.6.

Old MemoryView on v1.6.4
![image](https://user-images.githubusercontent.com/25745502/195093256-e9ed3ae3-7c36-4e14-9300-72cc6a86ba3c.png)

New MemoryView on v1.6.6
![image](https://user-images.githubusercontent.com/25745502/195094040-590719b6-e753-4919-8bdb-ff2566b8be0e.png)

**Comment by haneefdm** [comment]
Hmmm. Looking at it now...Thanks for reporting

**Comment by haneefdm** [comment]
Can you try the latest version 0.0.14, please?

Should be in the marketplace now.

**Comment by rubenstar** [comment]
Fixed it for me! Thanks a lot!

**Comment by rubenstar** [comment]
Fixed it for me, thanks!

**Comment by meltdown03** [comment]
Fixed here as well
