### ISSUE TITLE
Misaligned rows when saving memory to file

### ISSUE THREAD

**Issue by danielaird27** [mcu-debug/memview#10]
As shown in the image below, when a user saves the memory as a file (txt file) using the "Save to file..." button in the "Memory" tab, the address column is misaligned with the data.

For example, the row with the address ending in 0x110 in the "Memory" tab in VSCode shows byte 0 as 0x43 but the saved file shows that same byte at the address ending in 0x100 instead.

![proof](https://user-images.githubusercontent.com/57294055/216145916-e86d5148-d0a1-4bd1-b7fb-29eecdebab98.png)

**Comment by haneefdm** [comment]
Hmmm Weird. The problem started in the first two rows. The first address is duplicated in the text output.

Were these shots taken at different times? I see another problem beyond misalignment. The misaligned row does not have same data for columns 0x04

**Comment by danielaird27** [comment]
Yes, they were taken at slightly different times, I just use them to showcase the misaligned rows. The data for columns 0x04 isn't an issue.

**Comment by haneefdm** [comment]
Thanks for confirming. I was super scared when I saw that.

**Comment by haneefdm** [comment]
Should be fixed. I pushed the update to the marketplace. You should be getting it in a few hours...

Please close this issue after confirming the fid.

**Comment by haneefdm** [comment]
Look for version V0.0.19

**Comment by danielaird27** [comment]
@haneefdm Sorry for the late reply, the issue is fixed, thank you!
