### ISSUE TITLE
Offset labels for 4/8-byte formats are incorrect

### ISSUE THREAD

**Issue by SurfCityMojo** [mcu-debug/memview#14]
This is an easy one... When viewing memory with Formats of 4-Byte or 8-Byte, the offset labels shown at the top should be shown in the range of 0 to 31 (0x1f), rather than two repeating sets of 0 to 15 (0x0f).
 
 - OS: Windows
 - Version of Memory View: 0.0.20
 - Debugger Type: cortex-debug
 - Debugger Version: 1.10.0

**Comment by haneefdm** [comment]
Thanks for reporting the issue. Should be fixed now....
