### ISSUE TITLE
show wrong data 

### ISSUE THREAD

**Issue by hongshui3000** [mcu-debug/memview#2]
The data at 0x10000000 address is 0x96f3b83d, but the memview shows all 0s
![image](https://user-images.githubusercontent.com/25566498/195556683-a09cfea0-96ea-4d6e-861f-97600006efad.png)
![image](https://user-images.githubusercontent.com/25566498/195556728-f6b01e2e-3fe0-4dd3-a9c6-84872c99641b.png)
log：
[logs.txt](https://github.com/mcu-debug/memview/files/9774971/logs.txt)

**Comment by haneefdm** [comment]
Is this with the latest version of this extension? Please check to make sure you are using the latest 0.0.14+

I am thinking this is the same as #1

**Comment by hongshui3000** [comment]
> Is this with the latest version of this extension? Please check to make sure you are using the latest 0.0.14+
> 
> I am thinking this is the same as #1

![image](https://user-images.githubusercontent.com/25566498/195750326-5f1cb2df-65c1-4162-9108-ac1a688a8f63.png)

**Comment by haneefdm** [comment]
That is not my extension!!?!? Ours extension id is mcu-debug.memory-view (MemoryView)

Please make sure you uninstall the OBSOLETE MemoryView -- haneefdm.memview

**Comment by hongshui3000** [comment]
Updating to the latest extension seems to work
