### ISSUE TITLE
Data not refreshing

### ISSUE THREAD

**Issue by diggit** [mcu-debug/memview#20]
**Describe the bug**
Memory view is not refreshing data. Not even on after clicking "refresh data" icon. Fresh data are loaded only when a new memory view is created.

**To Reproduce**
1. create memory view of some valid memory address
2. change value from debugger
3. value updates in watch, but not in memory view
4. click update data in memory view, it flashes like it's doing something
5. old data are displayed
6. delete memory view
7. create new memory view of same address
8. displayed data are up to date and match current state

**Expected behavior**
Values update

**Screenshots**
Watch
![image](https://github.com/mcu-debug/memview/assets/512025/92e36269-043e-4f3e-bc0b-cb73eb2a8943)

Memory view
![image](https://github.com/mcu-debug/memview/assets/512025/2a9504ad-5fcc-4450-9410-4a7542eee1ab)

GDB command
```
set {uint32_t}0x20000370 = 0x12345678
```
Watch
![image](https://github.com/mcu-debug/memview/assets/512025/a7c990fc-faeb-4a6d-bbd5-9400d840d103)

Memory view (clicked update data icon)
![image](https://github.com/mcu-debug/memview/assets/512025/2b8be02b-3d10-436f-9ae4-9ef76620f3c3)

Memory view (deleted and created new on same address)
![image](https://github.com/mcu-debug/memview/assets/512025/f6807c45-9e9c-40af-81b0-9ca0d977a22e)

**Environment:**
 - OS: Arch Linux
 - Version of Memory View (this extension): v0.2.24
 - Debugger Type: cortex-debug
 - Debugger Version: v1.12.1

**Additional context**
J-link, Cortex M33 (STM32L552), non secure

**Comment by haneefdm** [comment]
If you change a value while the debugger is stopped, we don't get a notification of that. Or, if it changes some other way. We only refresh when the debugger halts because of a breakpoint/refresh. Sorry.

This is why there is a Refresh button <img width="29" alt="image" src="https://github.com/mcu-debug/memview/assets/41269583/3c2d73cf-d893-43d0-b617-9e116839d366"> So, are you saying that the Refresh button is not working?

**Comment by diggit** [comment]
> If you change a value while the debugger is stopped, we don't get a notification of that.
Watch values get refreshed even on every GDB command. That is not possible for memory view?

> This is why there is a Refresh button image So, are you saying that the Refresh button is not working?
Yes, displayed data remain the same after clicking that refresh icon. Resume/pause/stepping triggers memory view data refresh correctly.

**Comment by haneefdm** [comment]
>> Watch values get refreshed even on every GDB command. That is not possible for memory view?

Nope. MS controls the Watch/Variable/Stack windows. No one outside knows what is going on. Not even the debugger/adapter (like Cortex-Debug, cppdbg) knows what is going on. Certain actions in the debug console or variables windows can trigger a refresh...but not to all clients of the debugger.

I will see why the Refresh button not working as intended.

**Comment by haneefdm** [comment]
The Refresh button is working just fine for me. I cannot reproduce your problem. We are displaying whatever your debugger is reporting. I am assuming you are using Cortex-Debug. If so,

* Set `"showDevDebugOutput": "raw"` in your launch.json
* Do your normal debugging.
* Make sure your Memory View is exposed and it is displaying the right address/data rows
* Modify the memory value
* Switch to the 'Debug Console',  and clear the contents (Right Click and select `Clear Console`
* Switch to the Memory View and hit the Refresh button <img width="24" alt="image" src="https://github.com/mcu-debug/memview/assets/41269583/1725dead-00b0-4907-bba2-4a2d9c39369e">

* Switch back to the `Debug Console`. You should see new memory read requests being made. If you don't see that, we have an issue. If you see memory reads, check the values.

If you are using some other debugger, do whatever it takes to do something similar to above.

**Comment by haneefdm** [comment]
No feedback...
