### ISSUE TITLE
Unable to open mem view

### ISSUE THREAD

**Issue by hongshui3000** [mcu-debug/memview#3]
![image](https://user-images.githubusercontent.com/25566498/195558079-bea4fa41-b467-4fc6-96db-85748f6d4cf2.png)
log：
[log2.txt](https://github.com/mcu-debug/memview/files/9775057/log2.txt)

**Comment by haneefdm** [comment]
Steps to reproduce please?

**Comment by haneefdm** [comment]
Zero Info. I am closing this.
