### ISSUE TITLE
Not vertical layout friendly

### ISSUE THREAD

**Issue by diggit** [mcu-debug/memview#7]
Hi,
memview does not work well with high and narrow panels.

![image](https://user-images.githubusercontent.com/512025/198283833-44cd1f74-c5a6-4e70-bc42-99755f418274.png)

It automatically hides addresses and leaves ASCII decoding enabled. Top bar is not properly aligned with contents below.
I'd rather see addresses than ASCII decoding. Preferably configurable behavior.

Also, memview does not readjust its' width, when panel changes dimensions. Manual memview refresh has to be done.

It's great to see active development of memory view :)

**Comment by haneefdm** [comment]
Hmmm. Not even sure how this is possible. By any chance, the addresses showed up on far right?

>  Also, memview does not readjust its' width, when panel changes dimensions. Manual memview refresh has to be done.

Also, noted.

**Comment by haneefdm** [comment]
I cannot duplicate this issue. I can make it pretty narrow and it still works. Do you have steps to reproduce? What platform is it (although it is all the same HTML and the same browser). I also want to make sure you are using the right extension and are using the latest version. This extension's unique ID is `mcu-debug.memory-view`. I have an obsolete one but you will see that marked as such in the README for the extension.

<img width="381" alt="image" src="https://user-images.githubusercontent.com/41269583/198847367-1bc044d7-5274-4911-973f-cc8728947175.png">

**Comment by diggit** [comment]
Hi,
I have installed: mcu-debug.memory-view `v0.0.14` (Preview)

here are some details about behavior:

Moved panel to right, made it wide enough and refreshed memory view
![image](https://user-images.githubusercontent.com/512025/199263572-ccc225d3-dc31-449c-9e12-8067114ca7fb.png)

Shrunk a little bit. Individual addresses became scrollable.
![image](https://user-images.githubusercontent.com/512025/199264422-1a87c454-956c-4e94-a086-ddbd6327f0f7.png)

And even more...
![image](https://user-images.githubusercontent.com/512025/199264655-43b1f73b-3a94-484b-a87e-24464f7eba9f.png)

And then they completely disappear.
![image](https://user-images.githubusercontent.com/512025/199264881-0412225d-c169-4856-8a2a-c6efc463ad9a.png)

Memview becomes horizontally scrollable to fit contents and ascii decode, but addresses are nowhere to be seen.

I guess, something is missing "minimum width" property or so.

**Comment by haneefdm** [comment]
I pushed an update to the marketplace just now 0.0.16. See Changelog. The header does not horizontally scroll but the content does. We don't know what is wrong or how to fix it and seeking help from the community.

But, the vertical bar works pretty well in our testing.

Best we can do for now.

**Comment by haneefdm** [comment]
I am not gong to close this but please give us feedback if you have the time

**Comment by hongshui3000** [comment]
I am showing incomplete data here  0.0.16
![image](https://user-images.githubusercontent.com/25566498/202166943-5a5854be-bb45-4d0f-baea-961058137742.png)

**Comment by haneefdm** [comment]
@hongshui3000 Did you change the editor font-size in VSCode by any chance? Was this the same with the previous version? It appears that the line-height is not enough. I am not sure how to duplicate this.

Btw, this is a separate issue from the original issue of very narrow windows.

**Comment by hongshui3000** [comment]
font-size
![image](https://user-images.githubusercontent.com/25566498/202188228-10eba9cb-59fd-4838-9a03-effdd02906f8.png)

**Comment by haneefdm** [comment]
line spacing issue is fixed in latest release in the marketplace.

**Comment by haneefdm** [comment]
I am closing this for now. The horizontal scrolling could be a separate issue and not as pressing. The original issue has long been solved and I don't want people to use this issue to add other stuff.
