### ISSUE TITLE
Data regions are not refreshed synchronously

### ISSUE THREAD

**Issue by hongshui3000** [mcu-debug/memview#9]
![image](https://user-images.githubusercontent.com/25566498/202167353-5df1aa2c-22a2-43b3-ad52-2d2d4a3e192a.png)
Data regions are not refreshed synchronously

![image](https://user-images.githubusercontent.com/25566498/202167674-9e6bcc1e-67d2-4cd2-aa5a-8f08ab0ccfcb.png)
When I compile the address and display name

**Comment by hongshui3000** [comment]
、

> You changed both address and display name? 
yes，The data is not refreshed after the change


> Does a manual refresh (button) work?
yes

**Comment by haneefdm** [comment]
Should be fixed in the next update. The view contents will be updated only if
* The debugger session is in a 'stopped' state
* Or else it will be updated the next time the debugger enters the 'stopped' state -- an info bubble will pop up

**Comment by haneefdm** [comment]
Just released the update. If you change the expression, the window will update if the program is in the 'stopped' state.

You should also see the memory window update itself with proper line spacing as soon (tiny delay) as you change the font size.
